### ISSUE TITLE
Error with latest redux-observable version

### ISSUE THREAD

**Issue by mischkl** [angular-redux/redux-observable-decorator#18]
Attempting to compile when using the latest redux-observable results in the following error:

```bash
ERROR in [at-loader] ./node_modules/redux-observable-decorator/release/epic-decorator.d.ts:7:96 
        TS2344: Type 'T' does not satisfy the constraint 'Action'.
```

**Comment by mischkl** [comment]
I see there is already a pull request to fix this (#15) that's been open since August of last year. @e-schultz @SethDavenport could you please take a look at this?

**Comment by tcozzens** [comment]
I would like to +1 this - but with the idea that at this point, it would be beneficial to go to the new versions of redux-observable (at least beta) and redux of >4

@SethDavenport @e-schultz

**Comment by jamesbs** [comment]
Closing this as I believe this has been resolved by https://github.com/angular-redux/redux-observable-decorator/commit/2302dd8d57a037194acf9da218b1c53a024f5094
