### ISSUE TITLE
Compatibility with redux-observable 0.13.0

### ISSUE THREAD

**Issue by actra-gschuster** [angular-redux/redux-observable-decorator#6]
Interface of EpicMiddleware changed from `EpicMiddleware<T>` to `EpicMiddleware<T, S>`, created a pull request two days ago: https://github.com/angular-redux/redux-observable-decorator/pull/5

**Comment by e-schultz** [comment]
Thanks for the PR - just merged it in and did a publish. Since this is a breaking change, decided to do a version bump to 1.0 - thanks!

**Comment by e-schultz** [comment]
Closing this issue, thanks for the contribution - if you have any other issues / questions feel free to reach out.
